# Generated by Django 4.2.16 on 2024-11-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mileage', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('engine_size', models.FloatField()),
                ('transmission', models.CharField(max_length=50)),
                ('availability', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=100)),
                ('registration_date', models.DateField()),
                ('vin', models.CharField(max_length=100, unique=True)),
                ('year', models.PositiveIntegerField()),
                ('doors', models.PositiveIntegerField()),
                ('license_plate', models.CharField(max_length=20)),
            ],
        ),
    ]
