# Generated by Django 4.2.16 on 2024-11-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_testdriverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/'),
        ),
    ]
