# Generated by Django 4.2.16 on 2024-11-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel_consumption',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
