# Generated by Django 4.2.16 on 2024-11-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_fuel_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='history',
            field=models.TextField(blank=True),
        ),
    ]
