# Generated by Django 4.2.16 on 2024-11-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
