# Generated by Django 5.2 on 2025-04-28 10:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdriverequest',
            name='reservation_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testdriverequest',
            name='reservation_made_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='testdriverequest',
            name='test_drive_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
